My portfolio desktop version
PRATAP-KUMAR/My-Portfolio pull request #6
Opened 2022-07-08 09:05 UTC by PRATAP-KUMAR

the desktop version of "My portfolio" created.

2022-07-08 10:35 UTC, Chimwemwe-127001 requested changes
# Required Changes ♻️ :warning: 
### Hi @PRATAP-KUMAR

Good job so far! 👏 🎉 

There are some issues that you still need to work on to go to the next project but you are almost there! 

<img src="https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif" alt="so close">

## Highlights
- No linter errors :heavy_check_mark:
- Repo looks professional :briefcase:
- Solid pull request :scroll:

## Required Changes ♻️

***Check the comments under the review.***

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-08 10:35 UTC, Chimwemwe-127001 commented on index.html
> +		<section class='projects-section' id="projects-section">
- [ ] As the requirements suggest, consider replicating the design as much as possible (e.g., font, colors, images, text, margins) using [the info from the Figma templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). 

- Figam design
![FireShot Capture 005 - ▶ Template 1 - Microverse-Student-Project-1 - www figma com](https://user-images.githubusercontent.com/52143815/177973410-46161e91-997b-4c34-8094-97e5254cd894.png)

- Your Design
![FireShot Capture 001 - HTML 5 My Portfolio - raw githack com](https://user-images.githubusercontent.com/52143815/177973362-481a76ba-264b-44a0-8ddd-8468716db14f.png)

2022-07-08 10:35 UTC, Chimwemwe-127001 commented on desktop.css
> +}
- [ ] I've spotted a content overlapping issue, consider taking a look at it and fixing it before your next review.

![FireShot Capture 009 - HTML 5 My Portfolio - raw githack com](https://user-images.githubusercontent.com/52143815/177975634-0c748400-b258-45a1-ba5f-8c574e3b0bd4.png)

2022-07-09 06:22 UTC, roshan-bajgain requested changes
Hi @PRATAP-KUMAR, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 06:22 UTC, roshan-bajgain commented on style.css
>  }
- [ ] The page is divided half of it contains the project's picture and the other half contains the project's description but I found that description took more space kindly fix it so It occupies space equally.
- [ ] Kindly fix it in all the section that content image and descritption
### your design
![your](https://user-images.githubusercontent.com/81727988/178093954-c4b0b554-1221-42c9-97eb-263a31acb4d1.png)
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/178093961-4f461e53-494d-48a9-ac34-0a4a5193a79a.png)

2022-07-09 06:22 UTC, roshan-bajgain commented on style.css
> +}
- [ ] I would suggest you stick as much as possible to the Figma design's color, size, and font-family
### your design
![hsssssssssssssssssss](https://user-images.githubusercontent.com/81727988/178094116-e086fc1f-aa51-4d12-b4de-cdcd77ce4f3f.png)

### Figma design
![fffff](https://user-images.githubusercontent.com/81727988/178094123-91bc297f-6999-4d0c-a306-b358c3c7a362.png)

2022-07-09 06:22 UTC, roshan-bajgain commented on style.css
>  .contact-me-text {
- [ ] [Optional] The previous reviewer missed this so I am giving you an optional but kindly implement it. The elements of the form are centered on the page including the `Get in touch button.
- [ ]  [Optional]  Kindly increase the width of the form to make it match Figma's design.
- [ ]  [Optional]  your content is covering whole width but if you see in Figma design the content lies on middle of the page kindly fix it
### your design
![yourrrrr](https://user-images.githubusercontent.com/81727988/178094228-84e8b7d8-5850-420e-b58a-4647e6788723.png)
### Figma design
![your design](https://user-images.githubusercontent.com/81727988/178094239-d119fa7b-65cb-46d9-97b9-57760f5ef435.png)

2022-07-09 09:08 UTC, danielufeli approved these changes
Hi @PRATAP-KUMAR ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- No Linter Errors✔️
- Clean Code ✔️
- Clean Design ✔️
- Descriptive Readme ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 09:26 UTC, merged